### ISSUE TITLE
Support named arguments with spaces

### ISSUE THREAD

**Issue by ankurguptanit** [alexei/sprintf.js#104]
```javascipt
var user = {name: "Dolly", age: 24, 'in co': 23, '#':1}
undefined
sprintf("%(name)s - %(age)s", user)
"Dolly - 24"
sprintf("%(name)s - %(age)s - %(in co)s", user)
sprintf.js:146 Uncaught SyntaxError: [sprintf] failed to parse named argument key(…)b.parse @ sprintf.js:146b @ sprintf.js:19(anonymous function) @ VM50747:2InjectedScript._evaluateOn @ (program):878InjectedScript._evaluateAndWrap @ (program):811InjectedScript.evaluate @ (program):667
sprintf("%(name)s - %(age)s - %(#)s", user)
sprintf.js:151 Uncaught SyntaxError: [sprintf] failed to parse named argument key(…)
```

Can named arguments, object keys with spaces ('avg val') or special charaters (#, _ etc) be supported?

**Comment by alexei** [comment]
The named arguments feature was (is?) an experiment. I asked myself how would you access an object's properties, then noticed it was already implemented in Python, so I did something similar.

The implementation supports keys as generic ASCII variable names. For variable names, JavaScript - like many other languages - supports special characters like devanagari or cyrillic symbols. There are a few exceptions regarding reserved keywords, but generally speaking it supports just about any letter. In addition to that, it also allows for the `$` sign.
Now, regarding objects keys, I assume it supports just about everything that fits into a string, right? That includes things like `.`, `[`, `]`, `(`, `)` and `%` that I think would totally break the parser.

But suppose we reimplement the parser so that it consumes named arguments character by character and, somehow, gets past those shortcomings. Moving forward, suppose you have a format like `%(foo.bar[baz])s`. How many keys are in there: 1, 2 or 3?

That being said, currently I'm not really sure about your proposal. I think it would benefit if we added the `$` character. I myself use it inside variable names and this one's easy. It might also benefit if we added support for Unicode characters - how?

Beyond that, any other character raises questions I'm not sure I want to ask, let alone answer.

**Comment by alexei** [comment]
Also, I think adding them to the index access option would raise a couple of problems as well, which is why it's limited to natural numbers only.
