### ISSUE TITLE
What do you mean when you say sprintf.js is a "complete" sprintf implementation?

### ISSUE THREAD

**Issue by costacosta** [alexei/sprintf.js#117]
First let me say that I'm deeply appreciative of the effort you put in! 

I notice that even basic stuff like length modifiers are missing.  As an example: `%ld` is a common format that uses the `l` length modifier.  It's one of the basic format string elements, even K&R mentions it!

So I'm curious what you mean by complete.  Is there some spec you can point to?  Or do you merely mean complete relative to the README?

**Comment by alexei** [comment]
There are three reasons why I used that word, two of them historical I admit. Back in 2006-2007 when I wrote the first version I followed the PHP spec so it was complete in that regard. The second reason was that afaik (at least at the time and the following years) there were a couple of other JS implementations that only did basic `s` and `d` replacements and another one that went a bit further and implemented some of the features but lacked others. So again, it was "complete" compared to them and I think also on it's own since it covered a subset that's present in other languages. And finally - it's advertising. Now that I think of it, it seems right to raise this point. I think I hadn't touched that line in 10 years and never again thought about it. Maybe "full-featured" is more appropriate since it does mean more than simple replacements but doesn't mean "complete" (i.e. compared to the C spec). I might address this in the future and if you want to make a suggestion, please do.

Now, regarding the length modifier (and the C spec in general), some things that don't make sense in JS will not make it in, while others that don't exist in the C spec but do make sense in the JS world, will. For example I was inspired by Python to implement named placeholders support. So in the case of the length specifier, bear in mind that JS has numbers, end of story (i.e. no `int`s and `long`s), so the length sub specifier makes no sense.

**Comment by costacosta** [comment]
@alexei thanks for the quick reply!

> I followed the PHP spec so it was complete in that regard

That would be helpful to mention in the README or in the npm description or the github description.  PHP sprintf doesn't support length modifiers either, so it wouldn't be a flaw if `sprintf-js` didn't support it either.  More generally, when people talk about sprintf, it's generally the C99 or POSIX forms unless otherwise stated.

> Maybe "full-featured" is more appropriate since it does mean more than simple replacements but doesn't mean "complete" (i.e. compared to the C spec). I might address this in the future and if you want to make a suggestion, please do.

I think if you just mentioned PHP in the description it would be great (along with a link so we could follow along).

I would change the github project description to

> sprintf.js is a complete open source JavaScript implementation of PHP sprintf

That removes any ambiguity and makes the scope of the project extremely clear.  Even better, you can then set the bar for what constitutes a bug.  https://github.com/alexei/sprintf.js/issues/108 would be off-topic out the gate since PHP doesn't support variable width or precision. 

The NPM description probably should be

```
    "description": "JavaScript implementation of PHP sprintf",
```

And I would add a link to the PHP spec in the README:

> sprintf.js is a complete open source JavaScript implementation of [PHP's sprintf](http://php.net/manual/en/function.sprintf.php) for the browser and node.js.

FWIW You can keep the word "complete" and it wouldn't be false advertising so long as sprintf-js supports all of the features that PHP's sprintf supports.

**Comment by alexei** [comment]
The scope of this project was and is to make life a tad easier for me and everyone else who needs this sort of stuff. It was never supposed to blindly follow a spec. For purists, there are other projects that adhere to the grammar described by K&R.

Initially this library was advertised as following the PHP version but the project diverted a bit in the meantime so that statement was removed. As you can expect, I will not add it back again. What I will do, instead, is replace the term "complete" with another one.

Re #108 I think it's a good idea. As stated in my comment, I found myself needing it (though in a different language) so I'll see what I can do about it.
