### ISSUE TITLE
Bug parsing named arguments

### ISSUE THREAD

**Issue by sevketufuk** [alexei/sprintf.js#167]
Hi,
Basically the official documentation example
```javascript
var user = {
    name: 'Dolly',
}
sprintf('Hello %(name)s', user) 
``` 
at https://jsfiddle.net/0fzdctbt/1/ will work, however if you delete the `s` after `(%name)` and let the `%(name)` to be the last part of the string then this will fail with `[sprintf] unexpected placeholder` error.
```javascript
var user = {
    name: 'Dolly',
}
sprintf('Hello %(name)', user)
 ``` 
at https://jsfiddle.net/0fzdctbt/

**Comment by alexei** [comment]
Not sure I understand. What is the bug?

**Comment by alexei** [comment]
What should the result of
```
sprintf('Hello %(name)', {name: 'Dolly'})
```
be?

And if that's valid format, then
```
sprintf('Hello %(name)', {name: 'Dolly'}) == sprintf('Hello %', 'Dolly')
```
should be true, right?

If so, should `sprintf('Hello %s', 'girl')` yield `'Hello girl'` or `'Hello girls'`?

See also https://github.com/alexei/sprintf.js/pull/128

**Comment by sevketufuk** [comment]
You are right, I totally ignored purpose of `s` and treated it as `string` , my mistake!

**Comment by alexei** [comment]
Whether I'm right or not is not the point. The point is - do you now have a better grasp of what's going on? Do you understand the `sprintf` format, do you have a basic idea of how to parse the format, do you get it now (following my previous comment) why it works the way it works and what are the consequences of doing it otherwise?

And if you do, is there a suggestion you would like to make? For example, one might recommend that I update the readme to specify which element is optional and which is required. I never thought of that before, thinking the `sprintf` format is well known. Another idea would be to have it raise an error with a better message, one that says "hey, I tried parsing your placeholder, but I can't seem to find a valid type specifier". But this one's out of the question - the parser is too dumb to be that smart.
